-- Create site_content table
CREATE TABLE IF NOT EXISTS site_content (
    key TEXT NOT NULL,
    lang TEXT NOT NULL,
    value TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (key, lang)
);

-- Enable RLS
ALTER TABLE site_content ENABLE ROW LEVEL SECURITY;

-- Create policies for site_content
CREATE POLICY "Public can view site content" ON site_content
    FOR SELECT USING (true);

CREATE POLICY "Authenticated users can insert site content" ON site_content
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can update site content" ON site_content
    FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can delete site content" ON site_content
    FOR DELETE USING (auth.role() = 'authenticated');


-- Initial Data Migration
INSERT INTO site_content (key, lang, value) VALUES
('nav.home', 'pt', 'Home'),
('nav.photography', 'pt', 'Fotografia'),
('nav.graphicDesign', 'pt', 'Design Gráfico'),
('nav.about', 'pt', 'Sobre'),
('nav.services', 'pt', 'Serviços'),
('nav.contact', 'pt', 'Contato'),
('hero.title', 'pt', 'Tiago Damasceno'),
('hero.subtitle', 'pt', 'Fotógrafo & Designer Gráfico'),
('hero.description', 'pt', 'Retratos, arte, urbano, natureza, eventos & identidades visuais modernas'),
('hero.viewPortfolio', 'pt', 'Ver Portfólio'),
('hero.requestQuote', 'pt', 'Solicitar Orçamento'),
('portfolio.title', 'pt', 'Portfólio'),
('portfolio.description', 'pt', 'Uma coleção de momentos capturados através de diferentes perspectivas'),
('portfolio.categories.all', 'pt', 'Todos'),
('portfolio.categories.portraits', 'pt', 'Retratos'),
('portfolio.categories.urban', 'pt', 'Urbano'),
('portfolio.categories.nature', 'pt', 'Natureza'),
('portfolio.categories.art', 'pt', 'Arte'),
('portfolio.categories.events', 'pt', 'Eventos'),
('portfolio.loading', 'pt', 'Carregando fotos...'),
('portfolio.noPhotos', 'pt', 'Nenhuma foto encontrada. Use o painel admin para adicionar suas fotos!'),
('portfolio.goToAdmin', 'pt', 'Ir para Admin'),
('design.title', 'pt', 'Design Gráfico'),
('design.description', 'pt', 'Identidades visuais modernas, branding e peças de design que criam forte impacto visual e experiências memoráveis de marca'),
('design.categories.all', 'pt', 'Todos'),
('design.categories.logos', 'pt', 'Logos'),
('design.categories.visualIdentity', 'pt', 'Identidade Visual'),
('design.categories.socialMedia', 'pt', 'Redes Sociais'),
('design.categories.posters', 'pt', 'Pôsteres'),
('design.categories.special', 'pt', 'Projetos Especiais'),
('about.title', 'pt', 'Sobre Mim'),
('about.workTitle', 'pt', 'Sobre o Trabalho'),
('about.vision.title', 'pt', 'Visão Única'),
('about.vision.description', 'pt', 'Cada imagem conta uma história através de uma perspectiva autêntica e pessoal'),
('about.technique.title', 'pt', 'Técnica Refinada'),
('about.technique.description', 'pt', 'Domínio técnico combinado com sensibilidade artística'),
('about.passion.title', 'pt', 'Paixão Genuína'),
('about.passion.description', 'pt', 'Dedicação em capturar momentos que tocam emocionalmente'),
('about.paragraph1', 'pt', 'Fotografia é mais do que apenas capturar imagens. É sobre contar histórias, preservar momentos e criar conexões emocionais através da arte visual.'),
('about.paragraph2', 'pt', 'Cada projeto é abordado com dedicação, buscando sempre entregar trabalhos que superem expectativas e resistam ao teste do tempo.'),
('about.intro', 'pt', 'Sou Tiago Damasceno, fotógrafo e designer gráfico.'),
('about.description1', 'pt', 'Trabalho com retratos, fotografia urbana, natureza, arte e documentação de eventos, além de criar identidades visuais modernas e peças de design para marcas, empresas e projetos pessoais.'),
('about.description2', 'pt', 'Meu objetivo é entregar trabalhos com estilo, sensibilidade artística e forte impacto visual — tanto na fotografia quanto no design gráfico.'),
('about.expertise', 'pt', 'Expertise'),
('about.photography', 'pt', 'Fotografia'),
('about.photographyDesc', 'pt', 'Retratos, Urbano, Natureza, Arte e Documentação de Eventos'),
('about.graphicDesign', 'pt', 'Design Gráfico'),
('about.graphicDesignDesc', 'pt', 'Logos, Identidades Visuais, Redes Sociais e Branding'),
('about.quality', 'pt', 'Qualidade'),
('about.qualityDesc', 'pt', 'Comprometido em entregar trabalhos que excedem expectativas e resistem ao teste do tempo'),
('about.collaboration', 'pt', 'Colaboração'),
('about.collaborationDesc', 'pt', 'Trabalhando de perto com clientes para dar vida à sua visão'),
('about.creativity', 'pt', 'Criatividade'),
('about.creativityDesc', 'pt', 'Combinando maestria técnica com sensibilidade artística e inovação'),
('services.title', 'pt', 'Serviços'),
('services.description', 'pt', 'Serviços profissionais de fotografia e design gráfico adaptados às suas necessidades'),
('services.photographyServices', 'pt', 'Serviços de Fotografia'),
('services.photographyDesc', 'pt', 'Capturando momentos com visão artística e excelência técnica'),
('services.designServices', 'pt', 'Serviços de Design Gráfico'),
('services.designDesc', 'pt', 'Identidades visuais modernas e design que criam impressões duradouras'),
('services.readyToWork', 'pt', 'Pronto para Trabalhar Juntos?'),
('services.readyDesc', 'pt', 'Vamos dar vida à sua visão com serviços profissionais de fotografia e design'),
('services.getInTouch', 'pt', 'Entre em Contato'),
('services.photography.portraits.title', 'pt', 'Retratos'),
('services.photography.portraits.description', 'pt', 'Sessões profissionais de retratos capturando personalidade e emoção'),
('services.photography.portraits.features', 'pt', 'Retratos individuais,Sessões em família,Fotos profissionais,Retratos criativos'),
('services.photography.events.title', 'pt', 'Eventos'),
('services.photography.events.description', 'pt', 'Cobertura completa de eventos com documentação artística'),
('services.photography.events.features', 'pt', 'Casamentos,Eventos corporativos,Celebrações,Cobertura de conferências'),
('services.photography.urban.title', 'pt', 'Urbano & Arquitetura'),
('services.photography.urban.description', 'pt', 'Capturando a essência de paisagens urbanas e beleza arquitetônica'),
('services.photography.urban.features', 'pt', 'Paisagens urbanas,Fotografia de arquitetura,Imóveis,Fotografia de rua'),
('services.photography.nature.title', 'pt', 'Arte & Natureza'),
('services.photography.nature.description', 'pt', 'Fotografia artística e de natureza com visão criativa'),
('services.photography.nature.features', 'pt', 'Fotografia fine art,Fotografia de paisagem,Documentação da natureza,Projetos criativos'),
('services.design.identity.title', 'pt', 'Identidade Visual'),
('services.design.identity.description', 'pt', 'Sistemas completos de identidade de marca que causam impacto'),
('services.design.identity.features', 'pt', 'Design de logo,Manual de marca,Paletas de cores,Sistemas tipográficos'),
('services.design.branding.title', 'pt', 'Branding & Embalagens'),
('services.design.branding.description', 'pt', 'Soluções coesas de branding para produtos e serviços'),
('services.design.branding.features', 'pt', 'Design de embalagens,Estratégia de marca,Materiais de marketing,Design para impressão'),
('services.design.social.title', 'pt', 'Design para Redes Sociais'),
('services.design.social.description', 'pt', 'Conteúdo visual envolvente para plataformas digitais'),
('services.design.social.features', 'pt', 'Templates para redes sociais,Design de posts,Gráficos para stories,Calendários de conteúdo'),
('services.design.special.title', 'pt', 'Projetos Especiais'),
('services.design.special.description', 'pt', 'Soluções de design personalizadas para necessidades únicas'),
('services.design.special.features', 'pt', 'Design de pôsteres,Design editorial,Ilustração,Gráficos personalizados'),
('services.serviceOptions.select', 'pt', 'Selecione um serviço...'),
('services.serviceOptions.portrait', 'pt', 'Fotografia de Retratos'),
('services.serviceOptions.event', 'pt', 'Fotografia de Eventos'),
('services.serviceOptions.urban', 'pt', 'Fotografia Urbana'),
('services.serviceOptions.nature', 'pt', 'Fotografia de Natureza'),
('services.serviceOptions.logo', 'pt', 'Design de Logo'),
('services.serviceOptions.branding', 'pt', 'Identidade Visual & Branding'),
('services.serviceOptions.social', 'pt', 'Design para Redes Sociais'),
('services.serviceOptions.other', 'pt', 'Outro'),
('contact.title', 'pt', 'Entre em Contato'),
('contact.description', 'pt', 'Tem um projeto em mente? Vamos trabalhar juntos para criar algo incrível'),
('contact.sendMessage', 'pt', 'Enviar Mensagem'),
('contact.name', 'pt', 'Nome'),
('contact.email', 'pt', 'Email'),
('contact.phone', 'pt', 'Telefone'),
('contact.serviceInterest', 'pt', 'Interesse em Serviço'),
('contact.selectService', 'pt', 'Selecione um serviço...'),
('contact.message', 'pt', 'Mensagem'),
('contact.yourName', 'pt', 'Seu nome'),
('contact.yourEmail', 'pt', 'seu.email@exemplo.com'),
('contact.tellAboutProject', 'pt', 'Conte-me sobre seu projeto...'),
('contact.sending', 'pt', 'Enviando...'),
('contact.send', 'pt', 'Enviar Mensagem'),
('contact.contactInfo', 'pt', 'Informações de Contato'),
('contact.contactDesc', 'pt', 'Sinta-se à vontade para entrar em contato através de qualquer um destes canais. Eu normalmente respondo dentro de 24-48 horas.'),
('contact.location', 'pt', 'Localização'),
('contact.locationValue', 'pt', 'São Paulo, Brasil'),
('contact.followMe', 'pt', 'Siga-me'),
('contact.messageSent', 'pt', 'Mensagem Enviada!'),
('contact.thankYou', 'pt', 'Obrigado por entrar em contato. Entrarei em contato em breve.'),
('admin.panelTitle', 'pt', 'Painel Admin'),
('admin.login', 'pt', 'Login do Admin'),
('admin.loginDesc', 'pt', 'Digite suas credenciais para gerenciar o portfólio'),
('admin.password', 'pt', 'Senha'),
('admin.loggingIn', 'pt', 'Entrando...'),
('admin.logout', 'pt', 'Sair'),
('admin.photography', 'pt', 'Fotografia'),
('admin.designProjects', 'pt', 'Projetos de Design'),
('admin.addNew', 'pt', 'Adicionar Novo'),
('admin.uploadNew', 'pt', 'Fazer Upload Novo'),
('admin.delete', 'pt', 'Excluir'),
('admin.uploading', 'pt', 'Fazendo upload...'),
('admin.upload', 'pt', 'Upload'),
('admin.cancel', 'pt', 'Cancelar'),
('admin.category', 'pt', 'Categoria'),
('admin.titleField', 'pt', 'Título'),
('admin.descriptionField', 'pt', 'Descrição'),
('admin.year', 'pt', 'Ano'),
('admin.client', 'pt', 'Cliente'),
('admin.imageFile', 'pt', 'Arquivo de Imagem'),
('admin.images', 'pt', 'Imagens'),
('admin.optional', 'pt', 'opcional'),
('footer.brand', 'pt', 'Portfolio'),
('footer.tagline', 'pt', 'Capturando histórias visuais que inspiram e emocionam'),
('footer.contactTitle', 'pt', 'Contato'),
('footer.servicesTitle', 'pt', 'Serviços'),
('footer.portraitPhotography', 'pt', 'Fotografia de Retratos'),
('footer.urbanPhotography', 'pt', 'Fotografia Urbana'),
('footer.naturePhotography', 'pt', 'Fotografia de Natureza'),
('footer.events', 'pt', 'Eventos'),
('footer.commercialProjects', 'pt', 'Projetos Comerciais'),
('footer.allRightsReserved', 'pt', 'Todos os direitos reservados')
ON CONFLICT (key, lang) DO UPDATE SET value = EXCLUDED.value;
